<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelreview" nsURI="http://zoubek.bitandart.at/mervin/modelreview"
    nsPrefix="at.bitandart.zoubek.mervin">
  <eClassifiers xsi:type="ecore:EClass" name="ModelReview">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patchSets" upperBound="-1"
        eType="#//PatchSet" containment="true" eOpposite="#//PatchSet/review"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatchSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="review" eType="#//ModelReview"
        eOpposite="#//ModelReview/patchSets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patches" upperBound="-1"
        eType="#//Patch" eOpposite="#//Patch/patchSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newInvolvedModels" upperBound="-1"
        eType="#//ModelInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newInvolvedDiagrams" upperBound="-1"
        eType="#//DiagramInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldInvolvedModels" upperBound="-1"
        eType="#//ModelInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldInvolvedDiagrams" upperBound="-1"
        eType="#//DiagramInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelComparison" eType="ecore:EClass platform:/plugin/org.eclipse.emf.compare/model/compare.ecore#//Comparison"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagramComparison" eType="ecore:EClass platform:/plugin/org.eclipse.emf.compare/model/compare.ecore#//Comparison"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Patch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeType" eType="#//PatchChangeType"
        defaultValueLiteral="ADD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patchSet" eType="#//PatchSet"
        eOpposite="#//PatchSet/patches"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramPatch" eSuperTypes="#//Patch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newDiagramInstance" eType="#//DiagramInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldDiagramInstance" eType="#//DiagramInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelPatch" eSuperTypes="#//Patch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newModelInstance" eType="#//ModelInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oldModelInstance" eType="#//ModelInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootPackages" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramInstance" eSuperTypes="#//ModelInstance">
    <eOperations name="getDiagrams" upperBound="-1" eType="ecore:EClass ../../org.eclipse.gmf.runtime.notation/model/notation.ecore#//Diagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PatchChangeType">
    <eLiterals name="ADD"/>
    <eLiterals name="COPY" value="1"/>
    <eLiterals name="DELETE" value="2"/>
    <eLiterals name="MODIFY" value="3"/>
    <eLiterals name="RENAME" value="4"/>
  </eClassifiers>
</ecore:EPackage>
